[workspace]
members=["accumulative-hash","aoc-2025-01", "aoc-2025-02", "aoc-2025-03", "aoc-2025-05", "aoc-2025-06", "aoc-2025-07", "aoc-2025-08", "aoc-2025-09", "aoc-2025-10", "aoc-2025-11", "aoc-2025-12", "simple-graph", "tessellation-fill"]
resolver = "3"
