[package]
name = "aoc-2025-05"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
tikv-jemallocator = { version="0.6.1", optional=true }

[features]
default = []
profile = []
trace = []
jemalloc = ["dep-tikv-jemallocator"]
dep-tikv-jemallocator = ["tikv-jemallocator"]